# Generated by Django 4.2.5 on 2023-12-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0002_alter_personaldatamodel_prefecture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldatamodel',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='メールアドレス'),
        ),
    ]
