# Generated by Django 4.2.5 on 2023-12-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0005_alter_personaldatamodel_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldatamodel',
            name='hobby',
            field=models.JSONField(verbose_name='aabbcc'),
        ),
    ]
