# Generated by Django 4.2.5 on 2023-12-31 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0006_alter_personaldatamodel_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldatamodel',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='personaldatamodel',
            name='hobby',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='personaldatamodel',
            name='tel',
            field=models.CharField(default='', max_length=11, validators=[django.core.validators.RegexValidator(message="電話番号は数字で入力してください 例: '09012340001'", regex='^[0-9]+$'), django.core.validators.MinLengthValidator(11)]),
        ),
    ]
