# Generated by Django 4.2.5 on 2024-01-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0007_alter_personaldatamodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldatamodel',
            name='prefecture',
            field=models.TextField(choices=[('北海道', '北海道'), ('東京都', '東京都'), ('大阪府', '大阪府')], default='東京都'),
        ),
    ]
