# Generated by Django 4.2.5 on 2024-01-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0009_alter_personaldatamodel_prefecture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldatamodel',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='personaldatamodel',
            name='prefecture',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='personaldatamodel',
            name='sex',
            field=models.CharField(max_length=10),
        ),
    ]
