# Generated by Django 4.2.5 on 2024-01-02 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0010_alter_personaldatamodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldatamodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='personaldatamodel',
            name='food',
            field=models.JSONField(default=''),
        ),
        migrations.AlterField(
            model_name='personaldatamodel',
            name='hobby',
            field=models.JSONField(default=''),
        ),
        migrations.AlterField(
            model_name='personaldatamodel',
            name='tel',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="電話番号は数字で入力してください 例: '09012340001'", regex='^[0-9]+$'), django.core.validators.MinLengthValidator(11)]),
        ),
    ]
