# Generated by Django 4.2.5 on 2024-01-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0016_alter_personaldatamodel_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldatamodel',
            name='food',
            field=models.JSONField(null=True),
        ),
    ]
