# Generated by Django 4.2.5 on 2024-01-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0017_alter_personaldatamodel_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldatamodel',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='personaldatamodel',
            name='food',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='personaldatamodel',
            name='hobby',
            field=models.JSONField(default=[]),
        ),
    ]
