# Generated by Django 4.2.5 on 2024-01-02 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0021_alter_personaldatamodel_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldatamodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='personaldatamodel',
            name='food',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='personaldatamodel',
            name='hobby',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='personaldatamodel',
            name='tel',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='電話番号は数字で入力してください', regex='^[0-9]+$'), django.core.validators.MinLengthValidator(11)]),
        ),
    ]
